sudo: false
cache:
  yarn: true
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      rvm: 2.5.0
      node_js: false
      before_install:
        - nvm install 8
        - npm install -g yarn
      install:
        - yarn global add detox-cli
        - brew tap wix/brew
        - brew install --HEAD applesimutils
        - yarn
        - cd ios
        - bundle
        - cd ..
      script:
        - npm run bundle:ios
        - npm run test:e2e:build
        - npm run test:e2e
      deploy:
        on:
          branch: master
        provider: script
        script:
          - cd ios
          - fastlane alpha
    - language: android
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - nvm install 8
        - node --version
        - npm install -g yarn
        - yarn -version
      install:
        - yarn
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - build-tools-26.0.2
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleRelease
