language: node_js

node_js:
  - 8

sudo: false

cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - NODE_ENV='test'

script:
  - npm run bundle:ios

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode8.2
      node_js: false
      before_install:
        - nvm install 8
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/CliqzS.xcodeproj
      xcode_scheme: ios/CliqzSTests
      script:
        - cd ios
        - xcodebuild -scheme CliqzS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme CliqzS -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
    - language: android
      before_install:
        - nvm install 8
        - node --version
      install:
        - npm install
      android:
        components:
          - build-tools-23.0.1
          - build-tools-25.0.0
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleRelease
