language: node_js

sudo: false

cache:
  yarn: true

env:
  - NODE_ENV='test'

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      rvm: 2.5.0
      node_js: false
      before_install:
        - nvm install 8
        - node --version
        - npm install -g yarn appium-doctor
        - appium-doctor --ios
        - xcrun simctl list
        - exit 1
        - yarn -version
      install:
        - yarn
        - cd ios
        - bundle
      xcode_project: ios/CliqzS.xcodeproj
      xcode_scheme: ios/CliqzSTests
      script:
        - fastlane build
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then fastlane alpha; fi
      deploy:
        provider: script
        script:
          - echo "test deploy in the matrix"
    - language: android
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - nvm install 8
        - node --version
        - npm install -g yarn
        - yarn -version
      install:
        - yarn
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - build-tools-26.0.2
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleRelease
deploy:
  skip_cleanup: true
  provider: script
  script:
    - echo "test deploy"
  on:
    branch: master
