sudo: false
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      rvm: 2.5.0
      node_js: false
      before_install:
        - nvm install 8.9
        - npm install -g yarn
      install:
        - yarn global add detox-cli
        - brew tap wix/brew
        - brew install --HEAD applesimutils
        - npm install
        - cd ios
        - bundle
        - cd ..
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run bundle:ios; fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test:e2e:build; fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test:e2e; fi
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cd ios; fastlane alpha; fi
    - language: android
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - nvm install 8.9
        - node --version
        - npm install -g yarn
        - yarn -version
      install:
        - npm install
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - build-tools-26.0.2
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleRelease

    - language: node_js
      node_js: 8.9
      install:
        - npm install
      script:
        - npm run lint
