sudo: false
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      rvm: 2.5.0
      node_js: false
      before_install:
        - nvm install 8.9
        - npm install -g yarn
      install:
        - yarn global add detox-cli
        - brew tap wix/brew
        - brew install --HEAD applesimutils
        - npm install
        - cd ios
        - bundle
        - cd ..
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run bundle:ios; fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test:ios:e2e:build; fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test:ios:e2e; fi
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cd ios; fastlane alpha; fi
    - language: android
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - nvm install 8.9
        - node --version
        - npm install -g yarn
        - yarn -version
      install:
        - npm install
      android:
        components:
          - android-22
          - android-23
          - android-24
          - android-26
          - build-tools-23.0.1
          - build-tools-26.0.2
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
          - sys-img-armeabi-v7a-android-22
      before_script:
        - echo no | android create avd --force -n Nexus_5X_API_22 -t android-22 --abi armeabi-v7a
      script:
        - npm run test:android:e2e:build
        - npm run test:android:e2e
    - language: node_js
      node_js: 8.9
      install:
        - npm install
      script:
        - npm run lint
