export type UPDATE_WEBVIEW_ACTION = 'UPDATE_WEBVIEW_ACTION';
export const UPDATE_WEBVIEW_ACTION: UPDATE_WEBVIEW_ACTION = 'UPDATE_WEBVIEW_ACTION';

export type OPEN_LINK_ACTION = 'OPEN_LINK_ACTION';
export const OPEN_LINK_ACTION: OPEN_LINK_ACTION = 'OPEN_LINK_ACTION';

export type URLBAR_BLUR_ACTION = 'URLBAR_BLUR_ACTION';
export const URLBAR_BLUR_ACTION: URLBAR_BLUR_ACTION = 'URLBAR_BLUR_ACTION';

export type URLBAR_QUERY_ACTION = 'URLBAR_QUERY_ACTION';
export const URLBAR_QUERY_ACTION: URLBAR_QUERY_ACTION = 'URLBAR_QUERY_ACTION';

export type UPDATE_URLBAR_ACTION = 'UPDATE_URLBAR_ACTION';
export const UPDATE_URLBAR_ACTION: UPDATE_URLBAR_ACTION = 'UPDATE_URLBAR_ACTION';

export type GO_BACK_ACTION = 'GO_BACK_ACTION';
export const GO_BACK_ACTION: GO_BACK_ACTION = 'GO_BACK_ACTION';

export type GO_FORWARD_ACTION = 'GO_FORWARD_ACTION';
export const GO_FORWARD_ACTION: GO_FORWARD_ACTION = 'GO_FORWARD_ACTION';

export type BACK_FORWARD_RECEIVED_ACTION = 'BACK_FORWARD_RECEIVED_ACTION';
export const BACK_FORWARD_RECEIVED_ACTION: BACK_FORWARD_RECEIVED_ACTION =
  'BACK_FORWARD_RECEIVED_ACTION';

export type SET_HISTORY_ACTION = 'SET_HISTORY_ACTION';
export const SET_HISTORY_ACTION: SET_HISTORY_ACTION = 'SET_HISTORY_ACTION';

export type SET_MESSAGES_ACTION = 'SET_MESSAGES_ACTION';
export const SET_MESSAGES_ACTION: SET_MESSAGES_ACTION = 'SET_MESSAGES_ACTION';

export type SCREEN_CHANGE_ACTION = 'SCREEN_CHANGE_ACTION';
export const SCREEN_CHANGE_ACTION: SCREEN_CHANGE_ACTION = 'SCREEN_CHANGE_ACTION';

export type OPEN_DOMAIN_ACTION = 'OPEN_DOMAIN_ACTION';
export const OPEN_DOMAIN_ACTION: OPEN_DOMAIN_ACTION = 'OPEN_DOMAIN_ACTION';

export type SWITCH_TAB_ACTION = 'SWITCH_TAB_ACTION';
export const SWITCH_TAB_ACTION: SWITCH_TAB_ACTION = 'SWITCH_TAB_ACTION';
