# vim: ft=ruby

default_platform(:ios)

platform :ios do
  lane :build do
    sh 'cd .. && npm run bundle:ios'

    # existance of MATCH_PASSWORD env variable indicates this is a branch
    # build that will result in TestFlight upload
    if ENV["MATCH_PASSWORD"]
      increment_build_number(build_number: latest_testflight_build_number + 1)

      gym(
        configuration: "Release",
        scheme: "CliqzS",
      )
    else
      sh 'xcodebuild -scheme CliqzS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty'
      # The following does not work as it tries to build for Darwin,
      # probably to implicitly set `destination` xcodebuild param
      #gym(
      #  configuration: "Debug",
      #  scheme: "CliqzS",
      #  xcargs: "ONLY_ACTIVE_ARCH=NO",
      #  sdk: "iphonesimulator",
      #)
    end

  end

  lane :alpha do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "cliqzs",
      readonly: "true",
      verbose: "true",
    )

    upload_to_testflight(
      changelog: "Nightly build",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true",
    )
  end

end
