# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :alpha do
    # add actions here: https://docs.fastlane.tools/actions
   	sh 'cd .. && npm run bundle:ios'

 	match(git_branch: "cliqzs", readonly: "true")
 	
 	increment_build_number(build_number: latest_testflight_build_number + 1)
    
    gym(
  		configuration: "Release",
    	scheme: "CliqzS"
   	)

   	upload_to_testflight(
  		changelog: "Nightly build",
  		demo_account_required: "false",
  		skip_waiting_for_build_processing: "true"
  	)
  end
end
